name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Deploy to PyPI
        env:
          RELEASE_WEBHOOK: ${{ secrets.RELEASE_WEBHOOK }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install -U requests setuptools twine wheel -r requirements.txt
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*
          python release_webhook.py send_webhook
          output=$(python -c "import lightbulb, sys; sys.stdout.write(lightbulb.__version__)")
          echo "::set-output name=version::$output"
        id: deploy

      - name: Push Tag
        run: |
          tag="${{ steps.deploy.outputs.version }}"
          message="Release ${{ steps.deploy.outputs.version }}"
          git config user.name "${GITHUB_ACTOR}" && git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
